package Vistas;

import Entidades.*;
import conexion.*;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.time.*;
import java.util.*;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

public class ClienteVista extends javax.swing.JInternalFrame {
    DefaultTableModel modelo = new DefaultTableModel() {
        public boolean isCellEditable(int f, int c) {
            return false;
        }
    };
    
    Color azul = new Color(0, 107, 247);
    Color azulClaro = new Color(0, 173, 255);
    ClienteData cd = new ClienteData();
    MascotaData md = new MascotaData();

    
    public ClienteVista() {
        initComponents();
        cargarCombo();
        cargarTabla();
        cabecera();
        trans();//Aplicacion inclusiva
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        escritorioClientes = new javax.swing.JDesktopPane();
        jPanel2 = new javax.swing.JPanel();
        jCBClientes = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTMascotas = new javax.swing.JTable();
        jbeliminar = new javax.swing.JButton();
        jbmod = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTdni = new javax.swing.JTextField();
        jTapellido = new javax.swing.JTextField();
        jTnombre = new javax.swing.JTextField();
        jTdireccion = new javax.swing.JTextField();
        jTtelefono = new javax.swing.JTextField();
        jTnomaux = new javax.swing.JTextField();
        jTtelaux = new javax.swing.JTextField();
        jbRegMascota = new javax.swing.JButton();
        jbRegIstrar = new javax.swing.JButton();
        jbbuscar = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 0, 204));
        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/patita.jpg"))); // NOI18N
        setMinimumSize(new java.awt.Dimension(0, 0));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(977, 670));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 0, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Roboto Black", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/card_icon.png"))); // NOI18N
        jLabel1.setText("    Clientes");
        jLabel1.setToolTipText("");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(259, 259, 259)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(333, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 840, 50));

        jPanel4.setBackground(new java.awt.Color(0, 0, 204));
        jPanel4.setMinimumSize(new java.awt.Dimension(977, 670));
        jPanel4.setPreferredSize(new java.awt.Dimension(977, 670));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        escritorioClientes.setBackground(new java.awt.Color(255, 204, 204));
        escritorioClientes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jCBClientes.setModel(new javax.swing.DefaultComboBoxModel<>(new Cliente[] {  }));
        jCBClientes.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCBClientesItemStateChanged(evt);
            }
        });
        jPanel2.add(jCBClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 8, 263, -1));

        jTMascotas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTMascotas);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 320, 313));

        jbeliminar.setBackground(new java.awt.Color(51, 51, 255));
        jbeliminar.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jbeliminar.setForeground(new java.awt.Color(255, 255, 255));
        jbeliminar.setText("    ELIMINAR");
        jbeliminar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        jbeliminar.setBorderPainted(false);
        jbeliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jbeliminar.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jbeliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbeliminarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbeliminarMouseExited(evt);
            }
        });
        jbeliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbeliminarActionPerformed(evt);
            }
        });
        jPanel2.add(jbeliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, 150, 60));

        jbmod.setBackground(new java.awt.Color(51, 51, 255));
        jbmod.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jbmod.setForeground(new java.awt.Color(255, 255, 255));
        jbmod.setText("  MODIFICAR");
        jbmod.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        jbmod.setBorderPainted(false);
        jbmod.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jbmod.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jbmod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbmodMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbmodMouseExited(evt);
            }
        });
        jbmod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbmodActionPerformed(evt);
            }
        });
        jPanel2.add(jbmod, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 389, 140, 60));

        escritorioClientes.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(448, 6, 340, 490));

        jPanel1.setBackground(new java.awt.Color(0, 0, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("DNI:");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Apellido:");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nombre:");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Dirección:");

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Teléfono:");

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Persona Alternativa:");

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Telefono Alternativo:");

        jbRegMascota.setBackground(new java.awt.Color(51, 51, 255));
        jbRegMascota.setFont(new java.awt.Font("Roboto", 1, 30)); // NOI18N
        jbRegMascota.setForeground(new java.awt.Color(255, 255, 255));
        jbRegMascota.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/espacio-para-gatos.png"))); // NOI18N
        jbRegMascota.setText("     Registrar Mascota");
        jbRegMascota.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        jbRegMascota.setBorderPainted(false);
        jbRegMascota.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jbRegMascota.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jbRegMascota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbRegMascotaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbRegMascotaMouseExited(evt);
            }
        });
        jbRegMascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRegMascotaActionPerformed(evt);
            }
        });

        jbRegIstrar.setBackground(new java.awt.Color(51, 51, 255));
        jbRegIstrar.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jbRegIstrar.setForeground(new java.awt.Color(255, 255, 255));
        jbRegIstrar.setText("  REGISTRAR");
        jbRegIstrar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        jbRegIstrar.setBorderPainted(false);
        jbRegIstrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jbRegIstrar.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jbRegIstrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbRegIstrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbRegIstrarMouseExited(evt);
            }
        });
        jbRegIstrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRegIstrarActionPerformed(evt);
            }
        });

        jbbuscar.setBackground(new java.awt.Color(51, 51, 255));
        jbbuscar.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jbbuscar.setForeground(new java.awt.Color(255, 255, 255));
        jbbuscar.setText("      BUSCAR");
        jbbuscar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        jbbuscar.setBorderPainted(false);
        jbbuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jbbuscar.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jbbuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbbuscarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbbuscarMouseExited(evt);
            }
        });
        jbbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbbuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbRegMascota, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTdni))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTapellido))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTnombre)
                            .addComponent(jTdireccion)
                            .addComponent(jTtelefono)))
                    .addComponent(jTnomaux, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTtelaux, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbRegIstrar, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTdni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTapellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTdireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTtelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTnomaux, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTtelaux, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbbuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbRegIstrar, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbRegMascota, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        escritorioClientes.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, 490));

        jPanel4.add(escritorioClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 870, 570));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbbuscarActionPerformed
        // TODO add your handling code here:
        try {
            Cliente clibu = cd.buscarClientexdni(Integer.parseInt(jTdni.getText()));

        if (clibu != null) {
            jTapellido.setText(clibu.getApellido());
            jTnombre.setText(clibu.getNombre());
            jTdireccion.setText(clibu.getDireccion());
            jTtelefono.setText(String.valueOf(clibu.getTelefono()));
            jTnomaux.setText(clibu.getAltClie());
            jTtelaux.setText(String.valueOf(clibu.getAltTel()));
            
        } else {
            jTapellido.setText("");
            jTnombre.setText("");
            jTdireccion.setText("");
            jTtelefono.setText("");
            jTnomaux.setText("");
            jTtelaux.setText("");
            
        }

            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Error campos vacios o erroneos");
            jTdni.setText("");
            jTdni.requestFocus();
        }
    }//GEN-LAST:event_jbbuscarActionPerformed

    private void jbbuscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbbuscarMouseExited
        // TODO add your handling code here:
        jbbuscar.setOpaque(false);
    }//GEN-LAST:event_jbbuscarMouseExited

    private void jbbuscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbbuscarMouseEntered
        // TODO add your handling code here:
        jbbuscar.setOpaque(true);
        jbbuscar.setBackground(azulClaro);
    }//GEN-LAST:event_jbbuscarMouseEntered

    private void jbRegIstrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRegIstrarActionPerformed
        // TODO add your handling code here:
        try {
            int dni = Integer.parseInt(jTdni.getText());
            String ape = jTapellido.getText();
            String nom = jTnombre.getText();
            String dire = jTdireccion.getText();
            int tel = Integer.parseInt(jTtelefono.getText());
            String nomAux = jTnomaux.getText();
            int telAux = Integer.parseInt(jTtelaux.getText());

            Cliente c = new Cliente(dni, ape, nom, dire, tel, nomAux, telAux);
            cd.altaCliente(c);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Campos vacios o incorrectos");
            jTdni.requestFocus();
        }
    }//GEN-LAST:event_jbRegIstrarActionPerformed

    private void jbRegIstrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbRegIstrarMouseExited
        // TODO add your handling code here:
        jbRegIstrar.setOpaque(false);
    }//GEN-LAST:event_jbRegIstrarMouseExited

    private void jbRegIstrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbRegIstrarMouseEntered
        // TODO add your handling code here:
        jbRegIstrar.setOpaque(true);
        jbRegIstrar.setBackground(azulClaro);
    }//GEN-LAST:event_jbRegIstrarMouseEntered

    private void jbRegMascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRegMascotaActionPerformed
        // TODO add your handling code here:
        escritorioClientes.remove(jPanel1);
        escritorioClientes.repaint();
        DeClienteAMascota mv = new DeClienteAMascota();
        mv.setVisible(true);
        escritorioClientes.add(mv);
        escritorioClientes.moveToFront(mv);
    }//GEN-LAST:event_jbRegMascotaActionPerformed

    private void jbRegMascotaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbRegMascotaMouseExited
        jbRegMascota.setOpaque(false);
    }//GEN-LAST:event_jbRegMascotaMouseExited

    private void jbRegMascotaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbRegMascotaMouseEntered
        jbRegMascota.setOpaque(true);
        jbRegMascota.setBackground(azulClaro);
    }//GEN-LAST:event_jbRegMascotaMouseEntered

    private void jbmodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbmodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbmodActionPerformed

    private void jbmodMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbmodMouseExited
        // TODO add your handling code here:
        jbmod.setOpaque(false);
    }//GEN-LAST:event_jbmodMouseExited

    private void jbmodMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbmodMouseEntered
        // TODO add your handling code here:
        jbmod.setOpaque(true);
        jbmod.setBackground(azulClaro);
    }//GEN-LAST:event_jbmodMouseEntered

    private void jbeliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbeliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbeliminarActionPerformed

    private void jbeliminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbeliminarMouseExited
        // TODO add your handling code here:
        jbeliminar.setOpaque(false);
    }//GEN-LAST:event_jbeliminarMouseExited

    private void jbeliminarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbeliminarMouseEntered
        // TODO add your handling code here:
        jbeliminar.setOpaque(true);
        jbeliminar.setBackground(azulClaro);
    }//GEN-LAST:event_jbeliminarMouseEntered

    private void jCBClientesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCBClientesItemStateChanged
        // TODO add your handling code here:
        cargarTabla();
    }//GEN-LAST:event_jCBClientesItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorioClientes;
    private javax.swing.JComboBox<Cliente> jCBClientes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTMascotas;
    private javax.swing.JTextField jTapellido;
    private javax.swing.JTextField jTdireccion;
    private javax.swing.JTextField jTdni;
    private javax.swing.JTextField jTnomaux;
    private javax.swing.JTextField jTnombre;
    private javax.swing.JTextField jTtelaux;
    private javax.swing.JTextField jTtelefono;
    private javax.swing.JButton jbRegIstrar;
    private javax.swing.JButton jbRegMascota;
    private javax.swing.JButton jbbuscar;
    private javax.swing.JButton jbeliminar;
    private javax.swing.JButton jbmod;
    // End of variables declaration//GEN-END:variables

    private void cargarCombo(){
    for(Cliente clie: cd.listarClientes()){
        jCBClientes.addItem(clie);
    }
}
    private void cabecera() {

        modelo.addColumn("ID");
        modelo.addColumn("Alias");
        modelo.addColumn("Especie");
        modelo.addColumn("Sexo");

        jTMascotas.setModel(modelo);

        DefaultTableCellRenderer headerRenderer = (DefaultTableCellRenderer) jTMascotas.getTableHeader().getDefaultRenderer();
        headerRenderer.setHorizontalAlignment(SwingConstants.CENTER);
    }
    
    private void cargarTabla() {
        borrarFilas();
        Cliente cli = (Cliente) jCBClientes.getSelectedItem();
        int id = cli.getIdCliente();
        List<Mascota> reg = cd.mascotaXCliente(id);
        for (Mascota masc : reg) {

            modelo.addRow(new Object[]{
                masc.getIdMascota(),
                masc.getAlias(),
                masc.getEspecie(),
                masc.getSexo()
            });
        }
    }
    
    private void borrarFilas() {
        int filas = modelo.getRowCount() - 1;
        for (; filas >= 0; filas--) {
            modelo.removeRow(filas);
        }
    }
    
    public void trans() {
    jbbuscar.setOpaque(false);
        jbRegMascota.setContentAreaFilled(false);
        jbRegMascota.setBorderPainted(false);
        jbRegMascota.setOpaque(false);
        jbRegIstrar.setContentAreaFilled(false);
        jbRegIstrar.setBorderPainted(false);
        jbRegIstrar.setOpaque(false);
        jbbuscar.setContentAreaFilled(false);
        jbbuscar.setBorderPainted(false);
        jbeliminar.setOpaque(false);
        jbeliminar.setContentAreaFilled(false);
        jbeliminar.setBorderPainted(false);
        jbmod.setOpaque(false);
        jbmod.setContentAreaFilled(false);
        jbmod.setBorderPainted(false);
    }
}
