/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

import Entidades.Tratamiento;
import conexion.TratamientoData;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author cyka
 */
public class tratamienTodosVista extends javax.swing.JInternalFrame {

    DefaultTableModel modelo = new DefaultTableModel();

    TratamientoData td = new TratamientoData();

    /**
     * Creates new form tratamienTodosVista
     */
    public tratamienTodosVista() {
        initComponents();
        cargarCabecera();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTTratamientos = new javax.swing.JTable();
        jBModificar = new javax.swing.JButton();
        jBactivarDesactivar = new javax.swing.JButton();
        jBCerrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jRBTratActivos = new javax.swing.JRadioButton();
        jRBTratDesac = new javax.swing.JRadioButton();
        jRBTratTodos = new javax.swing.JRadioButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTTratamientos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTTratamientos.setToolTipText("");
        jScrollPane1.setViewportView(jTTratamientos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 130, 650, 240));

        jBModificar.setText("Desactivar/Activar");
        jBModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBModificarActionPerformed(evt);
            }
        });
        jPanel1.add(jBModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 140, 30));

        jBactivarDesactivar.setText("Modificar");
        jBactivarDesactivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBactivarDesactivarActionPerformed(evt);
            }
        });
        jPanel1.add(jBactivarDesactivar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 380, 140, 30));

        jBCerrar.setText("Cerrar");
        jBCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCerrarActionPerformed(evt);
            }
        });
        jPanel1.add(jBCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 473, 80, 20));

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("TRATAMIENTOS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 210, 40));

        jRBTratActivos.setText("Ver Activos");
        jRBTratActivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBTratActivosActionPerformed(evt);
            }
        });
        jPanel1.add(jRBTratActivos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 130, -1));

        jRBTratDesac.setText("Ver Desactivados");
        jRBTratDesac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBTratDesacActionPerformed(evt);
            }
        });
        jPanel1.add(jRBTratDesac, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 130, -1));

        jRBTratTodos.setText("Ver Todos");
        jRBTratTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBTratTodosActionPerformed(evt);
            }
        });
        jPanel1.add(jRBTratTodos, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, 130, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, -1, 750, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCerrarActionPerformed

        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jBCerrarActionPerformed

    private void jBModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBModificarActionPerformed
        // TODO add your handling code here:
        try {
            int indexFila = jTTratamientos.getSelectedRow();
            int idTr = (int) jTTratamientos.getValueAt(indexFila, 0);

            if (jTTratamientos.getValueAt(indexFila, 3).equals("Desactivo")) {
                td.modificarTratamientoEstadoActivado(idTr);
                jRBTratActivosActionPerformed(evt);
            } else {
                td.modificarTratamientoEstadoDesactivado(idTr);
                jRBTratDesacActionPerformed(evt);
            }
        } catch (ArrayIndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(this, "Datos sin seleccionar");
        }


    }//GEN-LAST:event_jBModificarActionPerformed

    private void jRBTratActivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBTratActivosActionPerformed
        // TODO add your handling code here:
        jRBTratDesac.setSelected(false);
        jRBTratTodos.setSelected(false);
        borrarFilas();
        if (jRBTratActivos.isSelected()) {
            List<Tratamiento> tratamientos = td.listarTratamiento();

            for (Tratamiento tratamiento : tratamientos) {
                modelo.addRow(new Object[]{tratamiento.getIdTratamiento(), tratamiento.getTipo(), tratamiento.getImporte(), tratamiento.isEstado()?"Activo":"Desactivo"});
            }
        }
    }//GEN-LAST:event_jRBTratActivosActionPerformed

    private void jRBTratDesacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBTratDesacActionPerformed
        // TODO add your handling code here:
        jRBTratActivos.setSelected(false);
        jRBTratTodos.setSelected(false);
        borrarFilas();
        if (jRBTratDesac.isSelected()) {
            List<Tratamiento> tratamientos = td.listarTratamientoInactivo();
            for (Tratamiento tratamiento : tratamientos) {
                modelo.addRow(new Object[]{tratamiento.getIdTratamiento(), tratamiento.getTipo(), tratamiento.getImporte(), tratamiento.isEstado()?"Activo":"Desactivo"});
            }
        }
    }//GEN-LAST:event_jRBTratDesacActionPerformed

    private void jRBTratTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBTratTodosActionPerformed
        // TODO add your handling code here:
        jRBTratActivos.setSelected(false);
        jRBTratDesac.setSelected(false);
        borrarFilas();
        if (jRBTratTodos.isSelected()) {
            List<Tratamiento> tratamientos = td.listarTodosTratamiento();

            for (Tratamiento tratamiento : tratamientos) {
                modelo.addRow(new Object[]{tratamiento.getIdTratamiento(), tratamiento.getTipo(), tratamiento.getImporte(), tratamiento.isEstado()?"Activo":"Desactivo"});
            }
        }
    }//GEN-LAST:event_jRBTratTodosActionPerformed

    private void jBactivarDesactivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBactivarDesactivarActionPerformed
        // TODO add your handling code here:
        
        try {
            int indexFila = jTTratamientos.getSelectedRow();
            int idTr = (int) jTTratamientos.getValueAt(indexFila, 0);
            String tipoMod = (String) jTTratamientos.getValueAt(indexFila, 1);
            int importeMod = Integer.parseInt((String)jTTratamientos.getValueAt(indexFila, 2)) ;
            
             if (tipoMod.equals("")) {
                JOptionPane.showMessageDialog(null, "Campos vacios o incorrectos");
            } else {
                 td.modificarTratamientoXId(idTr, tipoMod, importeMod);
            }
           
            borrarFilas();
        } catch (ArrayIndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(null, "No hay nada seleccionado");
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Campos vacios o incorrectos");
        } catch (ClassCastException e) {
            JOptionPane.showMessageDialog(null, "precio incorrecto");
        }
    }//GEN-LAST:event_jBactivarDesactivarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCerrar;
    private javax.swing.JButton jBModificar;
    private javax.swing.JButton jBactivarDesactivar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRBTratActivos;
    private javax.swing.JRadioButton jRBTratDesac;
    private javax.swing.JRadioButton jRBTratTodos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTTratamientos;
    // End of variables declaration//GEN-END:variables

    private void cargarCabecera() {
        modelo.addColumn("Id");
        modelo.addColumn("Tipo");
        modelo.addColumn("Importe");
        modelo.addColumn("Estado");
        jTTratamientos.setModel(modelo);
    }

    private void borrarFilas() {
        int filas = modelo.getRowCount() - 1;
        for (; filas >= 0; filas--) {
            modelo.removeRow(filas);
        }
    }
}
