/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

import Entidades.Tratamiento;
import conexion.TratamientoData;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author cyka
 */
public class tratamienTodosVista extends javax.swing.JInternalFrame {
    
    DefaultTableModel modelo = new DefaultTableModel();
    
    TratamientoData td = new TratamientoData();
    

    /**
     * Creates new form tratamienTodosVista
     */
    public tratamienTodosVista() {
        initComponents();
        cargarCabecera();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jCBTratamientosAct = new javax.swing.JCheckBox();
        jCBTratamientosDesac = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTTratamientos = new javax.swing.JTable();
        jBModificar = new javax.swing.JButton();
        jBactivarDesactivar = new javax.swing.JButton();
        jBEliminar = new javax.swing.JButton();
        jBCerrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jCBTratamientosAct.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jCBTratamientosAct.setForeground(new java.awt.Color(255, 255, 255));
        jCBTratamientosAct.setText("Ver tratamientos activos");
        jCBTratamientosAct.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCBTratamientosActItemStateChanged(evt);
            }
        });
        jPanel1.add(jCBTratamientosAct, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        jCBTratamientosDesac.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jCBTratamientosDesac.setForeground(new java.awt.Color(255, 255, 255));
        jCBTratamientosDesac.setText("Ver tratamientos desactivados");
        jPanel1.add(jCBTratamientosDesac, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 90, -1, -1));

        jTTratamientos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTTratamientos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 130, 650, 240));

        jBModificar.setText("Modificar");
        jPanel1.add(jBModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 140, 30));

        jBactivarDesactivar.setText("Desactivar/Activar");
        jPanel1.add(jBactivarDesactivar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 380, 140, 30));

        jBEliminar.setText("Eliminar");
        jBEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(jBEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 380, 140, 30));

        jBCerrar.setText("Cerrar");
        jBCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCerrarActionPerformed(evt);
            }
        });
        jPanel1.add(jBCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 473, 80, 20));

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("TRATAMIENTOS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 210, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, -1, 750, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCBTratamientosActItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCBTratamientosActItemStateChanged
        // TODO add your handling code here:
        List<Tratamiento> tratamientos = td.listarTratamiento();
        for (Tratamiento tratamiento : tratamientos) {
            modelo.addRow(new Object[]{tratamiento.getIdTratamiento(),tratamiento.getTipo(),tratamiento.getImporte(),tratamiento.isEstado()});
        }
    }//GEN-LAST:event_jCBTratamientosActItemStateChanged

    private void jBEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBEliminarActionPerformed

    private void jBCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCerrarActionPerformed
        
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jBCerrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCerrar;
    private javax.swing.JButton jBEliminar;
    private javax.swing.JButton jBModificar;
    private javax.swing.JButton jBactivarDesactivar;
    private javax.swing.JCheckBox jCBTratamientosAct;
    private javax.swing.JCheckBox jCBTratamientosDesac;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTTratamientos;
    // End of variables declaration//GEN-END:variables

    private void cargarCabecera() {
        modelo.addColumn("Id");
        modelo.addColumn("Tipo");
        modelo.addColumn("Importe");
        modelo.addColumn("Estado");
        jTTratamientos.setModel(modelo);
    }
}
